# GitHub Actions workflow
# https://help.github.com/en/actions/reference

name: Build

on:
  push:
    branches:
      - master
      - release/*
    tags:
      - release/*
  pull_request:
    branches:
      - master
      - release/*

env:
  # Minimize noise from dotnet CLI
  DOTNET_NOLOGO: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
        #url: https://github.com/actions/checkout

      - name: Configure .NET Core
        uses: actions/setup-dotnet@v1
        #url: https://github.com/actions/setup-dotnet
        with:
          dotnet-version: '5.0.x'

      - name: Stamp Version
        id: stamp
        run: >
          dotnet build .root.targets -c Release
          -p:StampOnBuild=true
          -p:Branch=${{ github.ref }}
          -p:Counter=${{ github.run_number }}
          -p:RepositoryCommit=${{ github.sha }}

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build
        run: >
          dotnet build --no-restore -c Release
          -p:PackageOutputPath=${{ runner.temp }}/dist

      - name: Save Package
        uses: actions/upload-artifact@v2
        #url: https://github.com/actions/upload-artifact
        with:
          name: Packages
          path: ${{ runner.temp }}/dist
          if-no-files-found: error
